# Common utilities: Status, Result<T>.
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "status",
    srcs = ["status.cc"],
    hdrs = ["status.h"],
)

cc_library(
    name = "result",
    hdrs = ["result.h"],
    deps = [":status"],
)

cc_library(
    name = "ids",
    hdrs = ["ids.h"],
)

cc_library(
    name = "checked_arithmetic",
    hdrs = ["checked_arithmetic.h"],
)

cc_test(
    name = "ids_test",
    srcs = ["ids_test.cc"],
    deps = [
        ":ids",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "status_test",
    srcs = ["status_test.cc"],
    deps = [
        ":status",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "result_test",
    srcs = ["result_test.cc"],
    deps = [
        ":result",
        "@googletest//:gtest_main",
    ],
)
