package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "simple_mp_pubsub",
    srcs = ["simple_mp_pubsub.cc"],
    deps = [
        "//mino/runtime:simple_node",
    ],
)

cc_binary(
    name = "simple_mp_pubsub_stress",
    srcs = ["simple_mp_pubsub_stress.cc"],
    deps = [
        "//mino/runtime:simple_node",
    ],
)
