// Generated by minoc. DO NOT EDIT.
#include "mino/schema/codegen/testdata/golden.generated.h"

namespace {
::mino::Result<std::vector<std::shared_ptr<const ::mino::schema::SchemaDescriptor>>> BuildWireDescriptors_be3ef505701671a9() noexcept {
    try {
        std::vector<std::shared_ptr<const ::mino::schema::SchemaDescriptor>> result;
        result.reserve(1u);
        result.push_back(std::make_shared<const ::mino::schema::SchemaDescriptor>(
            ::mino::schema::AggregateDescriptor(
                ::mino::schema::AggregateKind::kMessage,
                "golden.Telemetry",
                std::vector<::mino::schema::FieldDescriptor>{
                    ::mino::schema::FieldDescriptor(
                        1u, "sequence", ::mino::schema::FieldCardinality::kRequired,
                        ::mino::schema::TypeDescriptor::Scalar(::mino::schema::ScalarType::kUint32, "uint32"),
                        ::mino::schema::ConstraintSet(std::nullopt, std::nullopt, false), std::nullopt),
                    ::mino::schema::FieldDescriptor(
                        2u, "label", ::mino::schema::FieldCardinality::kOptional,
                        ::mino::schema::TypeDescriptor::Scalar(::mino::schema::ScalarType::kString, "string"),
                        ::mino::schema::ConstraintSet(std::optional<std::uint64_t>{16u}, std::nullopt, true), std::optional<::mino::schema::DefaultValue>{::mino::schema::DefaultValue(::mino::schema::DefaultValue::Kind::kString, "ready")}),
                    ::mino::schema::FieldDescriptor(
                        3u, "payload", ::mino::schema::FieldCardinality::kUnspecified,
                        ::mino::schema::TypeDescriptor::Scalar(::mino::schema::ScalarType::kBytes, "bytes"),
                        ::mino::schema::ConstraintSet(std::optional<std::uint64_t>{32u}, std::nullopt, false), std::nullopt),
                    ::mino::schema::FieldDescriptor(
                        4u, "samples", ::mino::schema::FieldCardinality::kUnspecified,
                        ::mino::schema::TypeDescriptor::Vector(::mino::schema::TypeDescriptor::Scalar(::mino::schema::ScalarType::kUint64, "uint64")),
                        ::mino::schema::ConstraintSet(std::nullopt, std::optional<std::uint64_t>{8u}, false), std::nullopt),
                    ::mino::schema::FieldDescriptor(
                        5u, "active", ::mino::schema::FieldCardinality::kOptional,
                        ::mino::schema::TypeDescriptor::Scalar(::mino::schema::ScalarType::kBool, "bool"),
                        ::mino::schema::ConstraintSet(std::nullopt, std::nullopt, false), std::nullopt),
                },
                std::vector<::mino::schema::ReservedRangeDescriptor>{
                    ::mino::schema::ReservedRangeDescriptor(6u, 7u),
                }),
            ::mino::schema::SchemaIdentity(
                0xa971167005f53ebeULL, ::mino::schema::CanonicalDigest{
                    std::byte{0xbe}, std::byte{0x3e}, std::byte{0xf5}, std::byte{0x05}, std::byte{0x70}, std::byte{0x16}, std::byte{0x71}, std::byte{0xa9}, std::byte{0xb9}, std::byte{0xa6}, std::byte{0xed}, std::byte{0x61}, std::byte{0xf4}, std::byte{0x19}, std::byte{0x0f}, std::byte{0xed}, std::byte{0xf2}, std::byte{0xbe}, std::byte{0x83}, std::byte{0xad}, std::byte{0xfe}, std::byte{0xb4}, std::byte{0x10}, std::byte{0xa4}, std::byte{0x06}, std::byte{0x7f}, std::byte{0xd8}, std::byte{0x7c}, std::byte{0x74}, std::byte{0xcc}, std::byte{0xe5}, std::byte{0x2f}
                }, 131073u, 1u),
            "mino-canonical-v1\000type:message:16:golden.Telemetry\n1:uint32:cardinality=required:-\n2:string:cardinality=optional,max_bytes=16,snapshot_key:string(5):ready\n3:bytes:cardinality=unspecified,max_bytes=32:-\n4:vector<uint64>:cardinality=unspecified,max_capacity=8:-\n5:bool:cardinality=optional:-\nreserved:6-7\n",
            std::vector<::mino::schema::DependencyDescriptor>{
            }));
        return result;
    } catch (const std::bad_alloc&) {
        return ::mino::Status::Error(::mino::StatusCode::kResourceExhausted);
    } catch (...) {
        return ::mino::Status::Error(::mino::StatusCode::kInternal);
    }
}
}  // namespace

static_assert(sizeof(::golden::Telemetry) == ::golden::Telemetry::kObjectSize);
static_assert(alignof(::golden::Telemetry) == ::golden::Telemetry::kObjectAlignment);
static_assert(std::is_standard_layout_v<::golden::Telemetry>);
static_assert(std::is_trivially_copyable_v<::golden::Telemetry>);
static_assert(std::is_trivially_default_constructible_v<::golden::Telemetry>);
static_assert(std::is_standard_layout_v<::golden::TelemetryObjectHeader>);

::mino::Result<::mino::schema::DynamicMessage> ::golden::TelemetryWireAdapter::ToDynamicMessage(
    const ::golden::Telemetry& value) noexcept {
    try {
        const ::golden::TelemetryAccessor accessor(value);
        if (!accessor.valid()) {
            return ::mino::Status::Error(::mino::StatusCode::kSchemaMismatch,
                                         "invalid generated SHM object");
        }
        if (accessor.unknown_fields().length != 0u) {
            return ::mino::Status::Error(::mino::StatusCode::kUnsupported,
                                         "static wire adapter cannot resolve unknown-field SHM storage");
        }
        ::mino::schema::DynamicMessage message;
        const ::mino::Status field_status_1 = message.SetField(1u, ::mino::schema::DynamicValue::Unsigned(accessor.sequence()));
        if (!field_status_1.ok()) return field_status_1;
        if (accessor.has_label()) {
            if (accessor.label().length != 0u) {
                return ::mino::Status::Error(::mino::StatusCode::kUnsupported,
                                             "static wire adapter cannot resolve non-empty variable SHM storage");
            }
            auto dynamic_2 = ::mino::schema::DynamicValue::String("");
            if (!dynamic_2.ok()) return dynamic_2.status();
            const ::mino::Status field_status_2 = message.SetField(2u, std::move(*dynamic_2));
            if (!field_status_2.ok()) return field_status_2;
        }
        if (accessor.payload().length != 0u) {
            return ::mino::Status::Error(::mino::StatusCode::kUnsupported,
                                         "static wire adapter cannot resolve non-empty variable SHM storage");
        }
        auto dynamic_3 = ::mino::schema::DynamicValue::Bytes(std::span<const std::byte>{});
        if (!dynamic_3.ok()) return dynamic_3.status();
        const ::mino::Status field_status_3 = message.SetField(3u, std::move(*dynamic_3));
        if (!field_status_3.ok()) return field_status_3;
        if (accessor.samples().length != 0u) {
            return ::mino::Status::Error(::mino::StatusCode::kUnsupported,
                                         "static wire adapter cannot resolve non-empty vector SHM storage");
        }
        auto vector_4 = std::make_shared<::mino::schema::DynamicVector>();
        auto dynamic_4 = ::mino::schema::DynamicValue::Vector(std::move(vector_4));
        if (!dynamic_4.ok()) return dynamic_4.status();
        const ::mino::Status field_status_4 = message.SetField(4u, std::move(*dynamic_4));
        if (!field_status_4.ok()) return field_status_4;
        if (accessor.has_active()) {
            const ::mino::Status field_status_5 = message.SetField(5u, ::mino::schema::DynamicValue::Boolean(accessor.active()));
            if (!field_status_5.ok()) return field_status_5;
        }
        return message;
    } catch (const std::bad_alloc&) {
        return ::mino::Status::Error(::mino::StatusCode::kResourceExhausted);
    } catch (...) {
        return ::mino::Status::Error(::mino::StatusCode::kInternal);
    }
}

::mino::Result<std::vector<std::byte>> ::golden::TelemetryWireAdapter::Encode(
    const ::golden::Telemetry& value,
    const ::mino::schema::WireLimits& limits) noexcept {
    auto message = ToDynamicMessage(value);
    if (!message.ok()) return message.status();
    auto descriptors = BuildWireDescriptors_be3ef505701671a9();
    if (!descriptors.ok()) return descriptors.status();
    return ::mino::schema::CanonicalWireCodec::Encode(
        **descriptors->begin(), *message, *descriptors, limits);
}

::mino::Result<::golden::Telemetry> ::golden::TelemetryWireAdapter::Decode(
    std::span<const std::byte> bytes,
    const ::mino::schema::WireLimits& limits) noexcept {
    auto descriptors = BuildWireDescriptors_be3ef505701671a9();
    if (!descriptors.ok()) return descriptors.status();
    auto message = ::mino::schema::CanonicalWireCodec::Decode(
        **descriptors->begin(), bytes, *descriptors, limits);
    if (!message.ok()) return message.status();
    if (!message->unknown_fields().fields().empty()) {
        return ::mino::Status::Error(::mino::StatusCode::kUnsupported,
                                     "static wire decode cannot allocate unknown-field SHM storage");
    }
    ::golden::Telemetry result;
    ::golden::TelemetryBuilder builder(result);
    if (const auto* field_1 = message->FindField(1u); field_1 != nullptr) {
        if (field_1->unsigned_integer() == nullptr) {
            return ::mino::Status::Error(::mino::StatusCode::kSchemaMismatch,
                                         "decoded dynamic scalar has wrong type");
        }
        builder.set_sequence(static_cast<std::uint32_t>(field_1->unsigned_integer()->value));
    }
    if (const auto* field_2 = message->FindField(2u); field_2 != nullptr) {
        if (field_2->string() == nullptr || !field_2->string()->value.empty()) {
            return ::mino::Status::Error(::mino::StatusCode::kUnsupported,
                                         "static wire decode cannot allocate non-empty string SHM storage");
        }
        if (!builder.set_label({.element_size = 1u})) {
            return ::mino::Status::Error(::mino::StatusCode::kSchemaMismatch);
        }
    }
    if (const auto* field_3 = message->FindField(3u); field_3 != nullptr) {
        if (field_3->bytes() == nullptr || !field_3->bytes()->value.empty()) {
            return ::mino::Status::Error(::mino::StatusCode::kUnsupported,
                                         "static wire decode cannot allocate non-empty bytes SHM storage");
        }
        if (!builder.set_payload({.element_size = 1u})) {
            return ::mino::Status::Error(::mino::StatusCode::kSchemaMismatch);
        }
    }
    if (const auto* field_4 = message->FindField(4u); field_4 != nullptr) {
        if (field_4->vector() == nullptr || field_4->vector()->value == nullptr ||
            !field_4->vector()->value->values().empty()) {
            return ::mino::Status::Error(::mino::StatusCode::kUnsupported,
                                         "static wire decode cannot allocate non-empty vector SHM storage");
        }
        if (!builder.set_samples({.element_size = 8u})) {
            return ::mino::Status::Error(::mino::StatusCode::kSchemaMismatch);
        }
    }
    if (const auto* field_5 = message->FindField(5u); field_5 != nullptr) {
        if (field_5->boolean() == nullptr) {
            return ::mino::Status::Error(::mino::StatusCode::kSchemaMismatch,
                                         "decoded dynamic scalar has wrong type");
        }
        builder.set_active(field_5->boolean()->value);
    }
    if (!::golden::TelemetryAccessor(result).valid()) {
        return ::mino::Status::Error(::mino::StatusCode::kSchemaMismatch,
                                     "decoded static object is invalid");
    }
    return result;
}
