// Generated by minoc. DO NOT EDIT.
// Stable SHM layout: all fields are accessed by compiler-planned byte offsets.

#ifndef MINO_GENERATED_MINO_SCHEMA_CODEGEN_TESTDATA_GOLDEN_GENERATED_H_6d888557aa07a919ae930ae0668680600556972796194bfd4e0b2bb9808bae16_
#define MINO_GENERATED_MINO_SCHEMA_CODEGEN_TESTDATA_GOLDEN_GENERATED_H_6d888557aa07a919ae930ae0668680600556972796194bfd4e0b2bb9808bae16_

#include <algorithm>
#include <array>
#include <bit>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <memory>
#include <new>
#include <optional>
#include <span>
#include <type_traits>
#include <utility>
#include <vector>

#include "mino/runtime/message_traits.h"
#include "mino/shm/channel/index_slot.h"
#include "mino/schema/wire.h"

namespace golden {

// Logical value returned by variable-field accessors. Its members are
// serialized individually; sizeof(TelemetryVariableMetadata) is not a format.
struct TelemetryVariableMetadata {
    std::uint64_t offset = 0;
    std::uint32_t generation = 0;
    std::uint32_t region_id = 0;
    std::uint64_t length = 0;
    std::uint64_t capacity = 0;
    std::uint64_t element_size = 0;
};

// Logical object-header value. The façade reads each member at its stable
// byte offset; this host value is never copied into the SHM format.
struct TelemetryObjectHeader {
    std::uint32_t layout_version = 0;
    std::uint32_t header_size = 0;
    std::uint64_t schema_short_id = 0;
    std::uint64_t object_size = 0;
    std::uint32_t field_count = 0;
    std::uint32_t presence_bitmap_words = 0;
};

struct alignas(8) Telemetry final {
    static constexpr std::size_t kObjectSize = 216;
    static constexpr std::size_t kFixedAreaSize = 136;
    static constexpr std::size_t kObjectAlignment = 8;
    static constexpr std::uint64_t kSchemaShortId = 0xa971167005f53ebeULL;
    static constexpr std::uint32_t kSchemaVersion = 131073u;
    static constexpr std::uint32_t kLayoutVersion = 1u;
    static constexpr std::array<std::uint8_t, 32> kSchemaDigest = {
        0xbe, 0x3e, 0xf5, 0x05, 0x70, 0x16, 0x71, 0xa9, 0xb9, 0xa6, 0xed, 0x61, 0xf4, 0x19, 0x0f, 0xed, 0xf2, 0xbe, 0x83, 0xad, 0xfe, 0xb4, 0x10, 0xa4, 0x06, 0x7f, 0xd8, 0x7c, 0x74, 0xcc, 0xe5, 0x2f
    };
    std::array<std::byte, kObjectSize> storage;
};

class TelemetryAccessor {
public:
    explicit TelemetryAccessor(const Telemetry& object) noexcept : data_(object.storage.data()), size_(object.storage.size()) {}
    explicit TelemetryAccessor(std::span<const std::byte> bytes) noexcept : data_(bytes.data()), size_(bytes.size()) {}
    TelemetryAccessor(const std::byte* data, std::size_t size) noexcept : data_(data), size_(size) {}

    std::uint32_t layout_version() const noexcept { return Load<std::uint32_t>(0); }
    std::uint32_t header_size() const noexcept { return Load<std::uint32_t>(4); }
    std::uint64_t schema_short_id() const noexcept { return Load<std::uint64_t>(8); }
    std::uint64_t object_size() const noexcept { return Load<std::uint64_t>(16); }
    std::uint32_t field_count() const noexcept { return Load<std::uint32_t>(24); }
    std::uint32_t presence_bitmap_words() const noexcept { return Load<std::uint32_t>(28); }
    TelemetryObjectHeader header() const noexcept {
        return {layout_version(), header_size(), schema_short_id(), object_size(),
                field_count(), presence_bitmap_words()};
    }

    std::uint32_t sequence() const noexcept { return Load<std::uint32_t>(40); }

    bool has_label() const noexcept {
        return (Load<std::uint64_t>(32) & (std::uint64_t{1} << 0)) != 0;
    }
    TelemetryVariableMetadata label() const noexcept { return ReadVariable(48); }

    TelemetryVariableMetadata payload() const noexcept { return ReadVariable(88); }

    TelemetryVariableMetadata samples() const noexcept { return ReadVariable(128); }

    bool has_active() const noexcept {
        return (Load<std::uint64_t>(32) & (std::uint64_t{1} << 1)) != 0;
    }
    bool active() const noexcept { return LoadByte(168) == 1; }

    TelemetryVariableMetadata unknown_fields() const noexcept {
        return ReadVariable(176u);
    }

    bool valid() const noexcept {
        if (data_ == nullptr || size_ < Telemetry::kObjectSize || layout_version() != Telemetry::kLayoutVersion || header_size() != 32u ||
            schema_short_id() != Telemetry::kSchemaShortId || object_size() != Telemetry::kFixedAreaSize ||
            field_count() != 5u || presence_bitmap_words() != 1u ||
            !UnusedPresenceBitsZero(2u, 1u)) return false;
        if (!has_label() && !IsZero(48u, 40u)) return false;
        if (has_label() && !ValidateBytes(label(), 16u)) return false;
        if (true && !ValidateBytes(payload(), 32u)) return false;
        if (true && !ValidateVector(samples(), 8u, 8u)) return false;
        if (!has_active() && !IsZero(168u, 1u)) return false;
        if (has_active() && LoadByte(168u) > 1u) return false;
        if (!ValidateUnknown(unknown_fields())) return false;
        return true;
    }

private:
    bool CanRead(std::size_t offset, std::size_t bytes) const noexcept {
        return data_ != nullptr && offset <= size_ && bytes <= size_ - offset;
    }
    std::uint8_t LoadByte(std::size_t offset) const noexcept {
        return CanRead(offset, 1) ? static_cast<std::uint8_t>(data_[offset]) : 0;
    }
    template <typename T> T Load(std::size_t offset) const noexcept {
        if (!CanRead(offset, sizeof(T))) return T{};
        std::array<std::byte, sizeof(T)> native{};
        for (std::size_t i = 0; i < sizeof(T); ++i) {
            const std::size_t index = std::endian::native == std::endian::little ? i : sizeof(T) - 1u - i;
            native[index] = data_[offset + i];
        }
        return std::bit_cast<T>(native);
    }
    bool IsZero(std::size_t offset, std::size_t bytes) const noexcept {
        if (!CanRead(offset, bytes)) return false;
        for (std::size_t i = 0; i < bytes; ++i) if (data_[offset + i] != std::byte{0}) return false;
        return true;
    }
    bool UnusedPresenceBitsZero(std::size_t used, std::size_t words) const noexcept {
        for (std::size_t bit = used; bit < words * 64u; ++bit) {
            if ((Load<std::uint64_t>(32u + (bit / 64u) * 8u) & (std::uint64_t{1} << (bit % 64u))) != 0) return false;
        }
        return true;
    }
    TelemetryVariableMetadata ReadVariable(std::size_t offset) const noexcept {
        if (!CanRead(offset, 40)) return {};
        return {Load<std::uint64_t>(offset), Load<std::uint32_t>(offset + 8),
                Load<std::uint32_t>(offset + 12), Load<std::uint64_t>(offset + 16),
                Load<std::uint64_t>(offset + 24), Load<std::uint64_t>(offset + 32)};
    }
    static bool ValidateBasic(const TelemetryVariableMetadata& value) noexcept {
        if (value.length > value.capacity) return false;
        return value.offset == 0 ? value.length == 0 && value.capacity == 0 : value.capacity != 0;
    }
    static bool ValidateBytes(const TelemetryVariableMetadata& value, std::uint64_t maximum) noexcept {
        return ValidateBasic(value) && value.element_size == 1 && value.capacity <= maximum;
    }
    static bool ValidateVector(const TelemetryVariableMetadata& value, std::uint64_t element_size, std::uint64_t maximum) noexcept {
        return ValidateBasic(value) && element_size != 0 && value.element_size == element_size && value.capacity <= maximum;
    }
    static bool ValidateNested(const TelemetryVariableMetadata& value, std::uint64_t object_size) noexcept {
        return value.offset != 0 && object_size != 0 && value.length == object_size &&
               value.capacity == object_size && value.element_size == 1;
    }
    static bool ValidateUnknown(const TelemetryVariableMetadata& value) noexcept {
        if (value.element_size != 0 || value.length > 64u || value.capacity > 66048u) return false;
        return value.length == 0 ? value.offset == 0 && value.capacity == 0
                                 : value.offset != 0 && value.capacity != 0;
    }
    const std::byte* data_ = nullptr;
    std::size_t size_ = 0;
};

class TelemetryBuilder {
public:
    explicit TelemetryBuilder(Telemetry& object) noexcept : object_(&object), data_(object.storage.data()) {
        std::fill(object.storage.begin(), object.storage.end(), std::byte{0});
        Store<std::uint32_t>(0, Telemetry::kLayoutVersion);
        Store<std::uint32_t>(4, 32u);
        Store<std::uint64_t>(8, Telemetry::kSchemaShortId);
        Store<std::uint64_t>(16, Telemetry::kFixedAreaSize);
        Store<std::uint32_t>(24, 5u);
        Store<std::uint32_t>(28, 1u);
    }
    Telemetry& object() noexcept { return *object_; }

    void set_sequence(std::uint32_t value) noexcept {
        Store<std::uint32_t>(40, value);
    }

    bool set_label(const TelemetryVariableMetadata& value) noexcept {
        if (value.length > value.capacity || value.capacity > 16u || value.element_size != 1u || (value.offset == 0 ? (value.length != 0 || value.capacity != 0) : value.capacity == 0)) return false;
        WriteVariable(48, value);
        SetPresence(0, true);
        return true;
    }
    void clear_label() noexcept {
        std::fill_n(data_ + 48, 40, std::byte{0});
        SetPresence(0, false);
    }

    bool set_payload(const TelemetryVariableMetadata& value) noexcept {
        if (value.length > value.capacity || value.capacity > 32u || value.element_size != 1u || (value.offset == 0 ? (value.length != 0 || value.capacity != 0) : value.capacity == 0)) return false;
        WriteVariable(88, value);
        return true;
    }

    bool set_samples(const TelemetryVariableMetadata& value) noexcept {
        if (value.length > value.capacity || value.capacity > 8u || value.element_size != 8u || (value.offset == 0 ? (value.length != 0 || value.capacity != 0) : value.capacity == 0)) return false;
        WriteVariable(128, value);
        return true;
    }

    void set_active(bool value) noexcept {
        data_[168] = value ? std::byte{1} : std::byte{0};
        SetPresence(1, true);
    }
    void clear_active() noexcept {
        std::fill_n(data_ + 168, 1, std::byte{0});
        SetPresence(1, false);
    }

private:
    template <typename T> void Store(std::size_t offset, T value) noexcept {
        const auto native = std::bit_cast<std::array<std::byte, sizeof(T)>>(value);
        for (std::size_t i = 0; i < sizeof(T); ++i) {
            const std::size_t index = std::endian::native == std::endian::little ? i : sizeof(T) - 1u - i;
            data_[offset + i] = native[index];
        }
    }
    void WriteVariable(std::size_t offset, const TelemetryVariableMetadata& value) noexcept {
        Store<std::uint64_t>(offset, value.offset);
        Store<std::uint32_t>(offset + 8, value.generation);
        Store<std::uint32_t>(offset + 12, value.region_id);
        Store<std::uint64_t>(offset + 16, value.length);
        Store<std::uint64_t>(offset + 24, value.capacity);
        Store<std::uint64_t>(offset + 32, value.element_size);
    }
    void SetPresence(std::size_t bit, bool present) noexcept {
        const std::size_t offset = 32u + (bit / 64u) * 8u;
        std::uint64_t word = 0;
        for (std::size_t i = 0; i < 8; ++i) word |= std::uint64_t{static_cast<std::uint8_t>(data_[offset + i])} << (i * 8u);
        const std::uint64_t mask = std::uint64_t{1} << (bit % 64u);
        word = present ? (word | mask) : (word & ~mask);
        Store<std::uint64_t>(offset, word);
    }
    Telemetry* object_;
    std::byte* data_;
};

// Canonical Wire adapter for fixed scalars and empty variable values.
// Non-empty variables, nested values, and unknown fields require SHM
// resolution/allocation and are rejected explicitly with kUnsupported.
class TelemetryWireAdapter final {
public:
    static ::mino::Result<::mino::schema::DynamicMessage> ToDynamicMessage(
        const Telemetry& value) noexcept;
    static ::mino::Result<std::vector<std::byte>> Encode(
        const Telemetry& value,
        const ::mino::schema::WireLimits& limits = {}) noexcept;
    static ::mino::Result<Telemetry> Decode(
        std::span<const std::byte> bytes,
        const ::mino::schema::WireLimits& limits = {}) noexcept;
};

}  // namespace golden

namespace mino {
template <> struct StaticMessageTraits<::golden::Telemetry> {
    static constexpr bool kIsSpecialized = true;
    static constexpr TypeId type_id{static_cast<std::uint32_t>(::golden::Telemetry::kSchemaShortId)};
    static constexpr std::uint32_t message_type = type_id.value;
    static constexpr std::uint32_t schema_version = ::golden::Telemetry::kSchemaVersion;
    static constexpr std::uint64_t schema_short_id = ::golden::Telemetry::kSchemaShortId;
    static constexpr std::uint32_t layout_version = ::golden::Telemetry::kLayoutVersion;
    static constexpr std::uint32_t index_flags = ::mino::kIndexSlotFlagHasChildSlabs;
    static Status Validate(const ::golden::Telemetry& value) noexcept {
        return ::golden::TelemetryAccessor(value).valid() ? Status::Ok() :
            Status::Error(StatusCode::kSchemaMismatch, "invalid generated SHM object");
    }
};
}  // namespace mino

#endif  // MINO_GENERATED_MINO_SCHEMA_CODEGEN_TESTDATA_GOLDEN_GENERATED_H_6d888557aa07a919ae930ae0668680600556972796194bfd4e0b2bb9808bae16_
