// Generated by minoc. DO NOT EDIT.
#include "mino/schema/codegen/testdata/golden.generated.h"

static_assert(sizeof(::golden::Telemetry) == ::golden::Telemetry::kObjectSize);
static_assert(alignof(::golden::Telemetry) == ::golden::Telemetry::kObjectAlignment);
static_assert(std::is_standard_layout_v<::golden::Telemetry>);
static_assert(std::is_trivially_copyable_v<::golden::Telemetry>);
static_assert(std::is_standard_layout_v<::golden::TelemetryObjectHeader>);
